FROM scratch

COPY --from=binary teamviewrelay-squaremap-source-client /teamviewrelay-squaremap-source-client
COPY --chown=65532:65532 docker-root/data /data
USER 65532:65532
ENTRYPOINT ["/teamviewrelay-squaremap-source-client"]
CMD ["--config", "/config/config.toml"]
