name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: MC-TeamViewer/TeamViewRelay-Protocol
          ref: proto/v0.6.4
          path: TeamViewRelay-Protocol
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          args: --locked --release --bins
        env:
          TEAMVIEWRELAY_PROTOCOL_DIR: ${{ github.workspace }}/TeamViewRelay-Protocol/proto
      - uses: actions/upload-artifact@v4
        with:
          name: teamviewrelay-squaremap-linux-x86_64
          path: |
            target/x86_64-unknown-linux-gnu/release/teamviewrelay-squaremap-source-client
            target/x86_64-unknown-linux-gnu/release/teamviewrelay-pass-cdn
          if-no-files-found: error
